config/routes.rb
Crm::Application.routes.draw do

  resources :categories

  resources :deal_milestones

  resources :tags

  resources :relationship_events

  resources :list_items

  resources :field_values

  resources :field_descriptions

  resources :entity_tags

  resources :entity_contacts

  resources :crm_contacts do
    resources :crm_contact_infos 
    resources :relationship_events 
    resources :tasks
    resources :deals
    resources :entity_tags
  end

  resources :tasks

  resources :deals do
    resources :relationship_events 
    resources :tasks
    resources :entity_contacts
    resources :entity_tags
  end

  resources :crm_cases do
    resources :relationship_events
    resources :tasks
    resources :entity_contacts
    resources :entity_tags
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :icon, :title
end

app/models/crm_case.rb
class CrmCase < ActiveRecord::Base
  attr_accessible :isClosed, :tenant_id, :title
  has_many :relationship_events, dependent: :destroy, :conditions => { :entity_type => 2 }, :foreign_key => "entity_id"
  has_many :tasks, dependent: :destroy, :conditions => { :entity_type => 2 }, :foreign_key => "entity_id"
  has_many :entity_tags, dependent: :destroy, :conditions => { :entity_type => 2 }, :foreign_key => "entity_id"
  has_many :entity_contacts, dependent: :destroy, :conditions => { :entity_type => 2 }, :foreign_key => "entity_id"
end

app/models/crm_contact.rb
class CrmContact < ActiveRecord::Base  
  attr_accessible :title, :company_id, :company_name, :first_name, :industry, :is_company, :last_name, :notes, :status_id, :tenant_id
  has_one :phone,  :class_name => "CrmContactInfo", :conditions => { :type_id => 0 }
  has_one :email,  :class_name => "CrmContactInfo", :conditions => { :type_id => 1 }
  has_many :crm_contact_infos, dependent: :destroy
  has_many :relationship_events, dependent: :destroy, :conditions => { :entity_type => 1 }, :foreign_key => "entity_id"
  has_many :tasks, dependent: :destroy, :conditions => { :entity_type => 1 }, :foreign_key => "entity_id"
  has_many :entity_tags, dependent: :destroy, :conditions => { :entity_type => 1 }, :foreign_key => "entity_id"
  has_many :deals
  belongs_to :company, :class_name => "CrmContact",  :foreign_key => "company_id"
  belongs_to :status, :class_name => "ListItem"
  def is_company_text
    ARRAY_CONTACT_TYPE[is_company][0]
  end
  def company_title
    company.title if company
  end
end

app/models/crm_contact_info.rb
class CrmContactInfo < ActiveRecord::Base
  # TYPES = [ {:1 => "Check", :2=>"Credit card", :3=>"Purchase order" }]
  belongs_to :tenant
  belongs_to :crm_contact
  attr_accessible :category_id, :contact_id, :tenant_id, :data, :is_primary, :type_id
  # validates :type, :inclusion =>   { :in => TYPES.keys.map(&:to_s) }
  def type
    @a=ARRAY_CONTACT_INFO_TYPE[type_id]
    @a[0] if @a
  end
  def category
    @a=ARRAY_CONTACT_INFO_CATEGORY[category_id]
    @a[0] if @a
  end
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  attr_accessible :actual_close_date, :bid_currency, :bid_type, :bid_value, :crm_contact_id, :deal_milestone_id, :deal_milestone_probability, :description, :expected_close_date, :per_period_value, :responsible, :tenant, :title
  has_many :relationship_events, dependent: :destroy, :conditions => { :entity_type => 3 }, :foreign_key => "entity_id"
  has_many :tasks, dependent: :destroy, :conditions => { :entity_type => 3 }, :foreign_key => "entity_id"
  has_many :entity_tags, dependent: :destroy, :conditions => { :entity_type => 3 }, :foreign_key => "entity_id"
  has_many :entity_contacts, dependent: :destroy, :conditions => { :entity_type => 3 }, :foreign_key => "entity_id"
end

app/models/deal_milestone.rb
class DealMilestone < ActiveRecord::Base
  belongs_to :tenant
  attr_accessible :color, :description, :probability, :sort_order, :status, :title
end

app/models/entity_contact.rb
class EntityContact < ActiveRecord::Base
  attr_accessible :entity_type, :crm_contact_id, :entity_id
  belongs_to :crm_contact
  def crm_contact111
    CrmContact.find(entity_contact.crm_contact_id).title
  end
end

app/models/entity_tag.rb
class EntityTag < ActiveRecord::Base
  attr_accessible :entity_id, :entity_type, :tag_id
  validates :tag_id, :uniqueness => { :scope => [:entity_id, :entity_type],
    :message => "should happen once per year" }
end

app/models/field_description.rb
class FieldDescription < ActiveRecord::Base
  attr_accessible :entity_type, :label, :mask, :sort_order, :tenant, :type
end

app/models/field_value.rb
class FieldValue < ActiveRecord::Base
  attr_accessible :entity, :entity_type, :field, :tenant, :value
end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  attr_accessible :additional_params, :color, :description, :list_type, :sort_order, :tenant, :title
end

app/models/relationship_event.rb
class RelationshipEvent < ActiveRecord::Base
  attr_accessible :category_id, :content, :crm_contact_id, :entity_type, :entity_id, :have_files, :tenant_id
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :entity_type, :tenant, :title
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :category_id, :crm_contact_id, :deadline, :description, :entity_id, :entity_type, :is_closed, :responsible_id, :tenant_id, :title
  belongs_to :category
  def entity_object
    EntityObjectByChild(self)
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  # GET /deals
  # GET /deals.json
  def index
    @deal = Deal.new
    case
    when params[:crm_contact_id]
      @EntityObject = CrmContact.find(params[:crm_contact_id])
      @deals = @EntityObject.deals
    else
    @deals = Deal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @deals }
    end
    end
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
    @deal = Deal.find(params[:id])
    @EntityObject=@deal
    @entity_tags=@EntityObject.entity_tags
    @entity_tag=EntityTag.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @deal }
    end
  end

  # GET /deals/new
  # GET /deals/new.json
  def new
    @deal = Deal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @deal }
    end
  end

  # GET /deals/1/edit
  def edit
    @deal = Deal.find(params[:id])
  end

  # POST /deals
  # POST /deals.json
  def create
    case
    when params[:crm_contact_id]
      @EntityObject = CrmContact.find(params[:crm_contact_id])
      @deal = @EntityObject.deals.create(params[:deal])
      @deals = @EntityObject.deals
    else
    @deal = Deal.new(params[:deal])

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render json: @deal, status: :created, location: @deal }
      else
        format.html { render action: "new" }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
    end
  end

  # PUT /deals/1
  # PUT /deals/1.json
  def update
    @deal = Deal.find(params[:id])

    respond_to do |format|
      if @deal.update_attributes(params[:deal])
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal = Deal.find(params[:id])
    @deal.destroy

    respond_to do |format|
      format.html { redirect_to deals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def currentpage(controller)
    "current" if params[:controller] == controller
  end
  def EntityObjectByChild(child)
    if child.entity_type
    case child.entity_type
    when 1
      CrmContact
    when 2
      CrmCase
    when 3
      Deal
    end.find(child.entity_id)
    end
  end
  def entity_object_path(entity_object)
     if entity_object then url_for(entity_object) else '' end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/crm_cases_helper.rb
module CrmCasesHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/deals/_form.html.erb
<%= form_for(case when @EntityObject then [@EntityObject, @EntityObject.deals.build] else @deal end, :remote =>  (@EntityObject != nil)) do |f| %>
  <% if @deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% @deal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :responsible %><br />
    <%= f.number_field :responsible %>
  </div>
  <div class="field">
    <%= f.label :crm_contact %><br />
    <%= f.text_field :crm_contact_id %>
  </div>
  <div class="field">
    <%= f.label :bid_currency %><br />
    <%= f.text_field :bid_currency %>
  </div>
  <div class="field">
    <%= f.label :bid_value %><br />
    <%= f.text_field :bid_value %>
  </div>
  <div class="field">
    <%= f.label :bid_type %><br />
    <%= f.number_field :bid_type %>
  </div>
  <div class="field">
    <%= f.label :deal_milestone %><br />
    <%= f.number_field :deal_milestone_id %>
  </div>
  <div class="field">
    <%= f.label :expected_close_date %><br />
    <%= f.datetime_select :expected_close_date %>
  </div>
  <div class="field">
    <%= f.label :per_period_value %><br />
    <%= f.number_field :per_period_value %>
  </div>
  <div class="field">
    <%= f.label :deal_milestone_probability %><br />
    <%= f.number_field :deal_milestone_probability %>
  </div>
  <div class="field">
    <%= f.label :actual_close_date %><br />
    <%= f.datetime_select :actual_close_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deals/_index.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Responsible</th>
    <th>Crm contact</th>
    <th>Bid currency</th>
    <th>Bid value</th>
    <th>Bid type</th>
    <th>Deal milestone</th>
    <th>Tenant</th>
    <th>Expected close date</th>
    <th>Per period value</th>
    <th>Deal milestone probability</th>
    <th>Actual close date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @deals.each do |deal| %>
  <tr>
    <td><%= deal.title %></td>
    <td><%= deal.description %></td>
    <td><%= deal.responsible %></td>
    <td><%= deal.crm_contact_id %></td>
    <td><%= deal.bid_currency %></td>
    <td><%= deal.bid_value %></td>
    <td><%= deal.bid_type %></td>
    <td><%= deal.deal_milestone_id %></td>
    <td><%= deal.expected_close_date %></td>
    <td><%= deal.per_period_value %></td>
    <td><%= deal.deal_milestone_probability %></td>
    <td><%= deal.actual_close_date %></td>
    <td><%= link_to 'Show', deal %></td>
    <td><%= link_to 'Edit', ( edit_deal_path(deal)) %></td>
    <td><%= link_to 'Destroy', deal, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<h1>Add</h1>

<%= render 'form' %>

app/views/deals/create.js.erb
$('#entity_detail').html("<%=j render 'index' %>");

app/views/deals/edit.html.erb
<h1>Editing deal</h1>

<%= render 'form' %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
<h1>Listing deals</h1>

<div id="entity_detail">
<%= render 'index' %>
</div>

app/views/deals/index.js.erb
$('#entity_detail').html("<%=j render 'index' %>");

app/views/deals/new.html.erb
<h1>New deal</h1>

<%= render 'form' %>

<%= link_to 'Back', deals_path %>

app/views/deals/show.html.erb
<%= link_to 'Edit', edit_deal_path(@deal) %> |
<%= link_to 'Back', deals_path %>
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @deal.title %>
</p>

<p>
  <b>Description:</b>
  <%= @deal.description %>
</p>

<p>
  <b>Responsible:</b>
  <%= @deal.responsible %>
</p>

<p>
  <b>Crm contact:</b>
  <%= @deal.crm_contact_id %>
</p>

<p>
  <b>Bid currency:</b>
  <%= @deal.bid_currency %>
</p>

<p>
  <b>Bid value:</b>
  <%= @deal.bid_value %>
</p>

<p>
  <b>Bid type:</b>
  <%= @deal.bid_type %>
</p>

<p>
  <b>Deal milestone:</b>
  <%= @deal.deal_milestone_id %>
</p>

<p>
  <b>Expected close date:</b>
  <%= @deal.expected_close_date %>
</p>

<p>
  <b>Per period value:</b>
  <%= @deal.per_period_value %>
</p>

<p>
  <b>Deal milestone probability:</b>
  <%= @deal.deal_milestone_probability %>
</p>

<p>
  <b>Actual close date:</b>
  <%= @deal.actual_close_date %>
</p>
<div id="tags">
<%= render "entity_tags/list" %>
</div>
<%= link_to "Events", (crm_case_path + relationship_events_path), :remote => true %>
<%= link_to "Tasks", (crm_case_path + tasks_path), :method => "get", :remote => true %>
<%= link_to "Participants", (crm_case_path + entity_contacts_path), :method => "get", :remote => true %>
<div id="entity_detail">
<%= render "relationship_events/events" %>
</div>