config/routes.rb
Crm::Application.routes.draw do

  resources :categories

  resources :deal_milestones

  resources :tags

  resources :relationship_events

  resources :list_items

  resources :field_values

  resources :field_descriptions

  resources :entity_tags

  resources :entity_contacts

  resources :crm_contacts do
    resources :crm_contact_infos 
    resources :relationship_events 
    resources :tasks
    resources :deals
    resources :entity_tags
  end

  resources :tasks

  resources :deals do
    resources :relationship_events 
    resources :tasks
    resources :entity_contacts
    resources :entity_tags
  end

  resources :crm_cases do
    resources :relationship_events
    resources :tasks
    resources :entity_contacts
    resources :entity_tags
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :icon, :title
end

app/models/crm_case.rb
class CrmCase < ActiveRecord::Base
  attr_accessible :isClosed, :tenant_id, :title
  has_many :relationship_events, dependent: :destroy, :conditions => { :entity_type => 2 }, :foreign_key => "entity_id"
  has_many :tasks, dependent: :destroy, :conditions => { :entity_type => 2 }, :foreign_key => "entity_id"
  has_many :entity_tags, dependent: :destroy, :conditions => { :entity_type => 2 }, :foreign_key => "entity_id"
  has_many :entity_contacts, dependent: :destroy, :conditions => { :entity_type => 2 }, :foreign_key => "entity_id"
end

app/models/crm_contact.rb
class CrmContact < ActiveRecord::Base  
  attr_accessible :title, :company_id, :company_name, :first_name, :industry, :is_company, :last_name, :notes, :status_id, :tenant_id
  has_one :phone,  :class_name => "CrmContactInfo", :conditions => { :type_id => 0 }
  has_one :email,  :class_name => "CrmContactInfo", :conditions => { :type_id => 1 }
  has_many :crm_contact_infos, dependent: :destroy
  has_many :relationship_events, dependent: :destroy, :conditions => { :entity_type => 1 }, :foreign_key => "entity_id"
  has_many :tasks, dependent: :destroy, :conditions => { :entity_type => 1 }, :foreign_key => "entity_id"
  has_many :entity_tags, dependent: :destroy, :conditions => { :entity_type => 1 }, :foreign_key => "entity_id"
  has_many :deals
  belongs_to :company, :class_name => "CrmContact",  :foreign_key => "company_id"
  belongs_to :status, :class_name => "ListItem"
  def is_company_text
    ARRAY_CONTACT_TYPE[is_company][0]
  end
  def company_title
    company.title if company
  end
end

app/models/crm_contact_info.rb
class CrmContactInfo < ActiveRecord::Base
  # TYPES = [ {:1 => "Check", :2=>"Credit card", :3=>"Purchase order" }]
  belongs_to :tenant
  belongs_to :crm_contact
  attr_accessible :category_id, :contact_id, :tenant_id, :data, :is_primary, :type_id
  # validates :type, :inclusion =>   { :in => TYPES.keys.map(&:to_s) }
  def type
    @a=ARRAY_CONTACT_INFO_TYPE[type_id]
    @a[0] if @a
  end
  def category
    @a=ARRAY_CONTACT_INFO_CATEGORY[category_id]
    @a[0] if @a
  end
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  attr_accessible :actual_close_date, :bid_currency, :bid_type, :bid_value, :crm_contact_id, :deal_milestone_id, :deal_milestone_probability, :description, :expected_close_date, :per_period_value, :responsible, :tenant, :title
  has_many :relationship_events, dependent: :destroy, :conditions => { :entity_type => 3 }, :foreign_key => "entity_id"
  has_many :tasks, dependent: :destroy, :conditions => { :entity_type => 3 }, :foreign_key => "entity_id"
  has_many :entity_tags, dependent: :destroy, :conditions => { :entity_type => 3 }, :foreign_key => "entity_id"
  has_many :entity_contacts, dependent: :destroy, :conditions => { :entity_type => 3 }, :foreign_key => "entity_id"
end

app/models/deal_milestone.rb
class DealMilestone < ActiveRecord::Base
  belongs_to :tenant
  attr_accessible :color, :description, :probability, :sort_order, :status, :title
end

app/models/entity_contact.rb
class EntityContact < ActiveRecord::Base
  attr_accessible :entity_type, :crm_contact_id, :entity_id
  belongs_to :crm_contact
  def crm_contact111
    CrmContact.find(entity_contact.crm_contact_id).title
  end
end

app/models/entity_tag.rb
class EntityTag < ActiveRecord::Base
  attr_accessible :entity_id, :entity_type, :tag_id
  validates :tag_id, :uniqueness => { :scope => [:entity_id, :entity_type],
    :message => "should happen once per year" }
end

app/models/field_description.rb
class FieldDescription < ActiveRecord::Base
  attr_accessible :entity_type, :label, :mask, :sort_order, :tenant, :type
end

app/models/field_value.rb
class FieldValue < ActiveRecord::Base
  attr_accessible :entity, :entity_type, :field, :tenant, :value
end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  attr_accessible :additional_params, :color, :description, :list_type, :sort_order, :tenant, :title
end

app/models/relationship_event.rb
class RelationshipEvent < ActiveRecord::Base
  attr_accessible :category_id, :content, :crm_contact_id, :entity_type, :entity_id, :have_files, :tenant_id
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :entity_type, :tenant, :title
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :category_id, :crm_contact_id, :deadline, :description, :entity_id, :entity_type, :is_closed, :responsible_id, :tenant_id, :title
  belongs_to :category
  def entity_object
    EntityObjectByChild(self)
  end
end

app/controllers/field_descriptions_controller.rb
class FieldDescriptionsController < ApplicationController
  # GET /field_descriptions
  # GET /field_descriptions.json
  def index
    @field_descriptions = FieldDescription.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @field_descriptions }
    end
  end

  # GET /field_descriptions/1
  # GET /field_descriptions/1.json
  def show
    @field_description = FieldDescription.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @field_description }
    end
  end

  # GET /field_descriptions/new
  # GET /field_descriptions/new.json
  def new
    @field_description = FieldDescription.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @field_description }
    end
  end

  # GET /field_descriptions/1/edit
  def edit
    @field_description = FieldDescription.find(params[:id])
  end

  # POST /field_descriptions
  # POST /field_descriptions.json
  def create
    @field_description = FieldDescription.new(params[:field_description])

    respond_to do |format|
      if @field_description.save
        format.html { redirect_to @field_description, notice: 'Field description was successfully created.' }
        format.json { render json: @field_description, status: :created, location: @field_description }
      else
        format.html { render action: "new" }
        format.json { render json: @field_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /field_descriptions/1
  # PUT /field_descriptions/1.json
  def update
    @field_description = FieldDescription.find(params[:id])

    respond_to do |format|
      if @field_description.update_attributes(params[:field_description])
        format.html { redirect_to @field_description, notice: 'Field description was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @field_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /field_descriptions/1
  # DELETE /field_descriptions/1.json
  def destroy
    @field_description = FieldDescription.find(params[:id])
    @field_description.destroy

    respond_to do |format|
      format.html { redirect_to field_descriptions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/crm_cases_helper.rb
module CrmCasesHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/field_descriptions_helper.rb
module FieldDescriptionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/field_descriptions/_form.html.erb
<%= form_for(@field_description) do |f| %>
  <% if @field_description.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@field_description.errors.count, "error") %> prohibited this field_description from being saved:</h2>

      <ul>
      <% @field_description.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tenant %><br />
    <%= f.text_field :tenant %>
  </div>
  <div class="field">
    <%= f.label :label %><br />
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :sort_order %><br />
    <%= f.number_field :sort_order %>
  </div>
  <div class="field">
    <%= f.label :mask %><br />
    <%= f.text_field :mask %>
  </div>
  <div class="field">
    <%= f.label :entity_type %><br />
    <%= f.number_field :entity_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/field_descriptions/edit.html.erb
<h1>Editing field_description</h1>

<%= render 'form' %>

<%= link_to 'Show', @field_description %> |
<%= link_to 'Back', field_descriptions_path %>

app/views/field_descriptions/index.html.erb
<h1>Listing field_descriptions</h1>

<table>
  <tr>
    <th>Tenant</th>
    <th>Label</th>
    <th>Type</th>
    <th>Sort order</th>
    <th>Mask</th>
    <th>Entity type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @field_descriptions.each do |field_description| %>
  <tr>
    <td><%= field_description.tenant %></td>
    <td><%= field_description.label %></td>
    <td><%= field_description.type %></td>
    <td><%= field_description.sort_order %></td>
    <td><%= field_description.mask %></td>
    <td><%= field_description.entity_type %></td>
    <td><%= link_to 'Show', field_description %></td>
    <td><%= link_to 'Edit', edit_field_description_path(field_description) %></td>
    <td><%= link_to 'Destroy', field_description, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Field description', new_field_description_path %>

app/views/field_descriptions/new.html.erb
<h1>New field_description</h1>

<%= render 'form' %>

<%= link_to 'Back', field_descriptions_path %>

app/views/field_descriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tenant:</b>
  <%= @field_description.tenant %>
</p>

<p>
  <b>Label:</b>
  <%= @field_description.label %>
</p>

<p>
  <b>Type:</b>
  <%= @field_description.type %>
</p>

<p>
  <b>Sort order:</b>
  <%= @field_description.sort_order %>
</p>

<p>
  <b>Mask:</b>
  <%= @field_description.mask %>
</p>

<p>
  <b>Entity type:</b>
  <%= @field_description.entity_type %>
</p>


<%= link_to 'Edit', edit_field_description_path(@field_description) %> |
<%= link_to 'Back', field_descriptions_path %>