config/routes.rb
Crm::Application.routes.draw do

  resources :categories

  resources :deal_milestones

  resources :tags

  resources :relationship_events

  resources :list_items

  resources :field_values

  resources :field_descriptions

  resources :entity_tags

  resources :entity_contacts

  resources :crm_contacts do
    resources :crm_contact_infos 
    resources :relationship_events 
    resources :tasks
    resources :deals
    resources :entity_tags
  end

  resources :tasks

  resources :deals do
    resources :relationship_events 
    resources :tasks
    resources :entity_contacts
    resources :entity_tags
  end

  resources :crm_cases do
    resources :relationship_events
    resources :tasks
    resources :entity_contacts
    resources :entity_tags
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :icon, :title
end

app/models/crm_case.rb
class CrmCase < ActiveRecord::Base
  attr_accessible :isClosed, :tenant_id, :title
  has_many :relationship_events, dependent: :destroy, :conditions => { :entity_type => 2 }, :foreign_key => "entity_id"
  has_many :tasks, dependent: :destroy, :conditions => { :entity_type => 2 }, :foreign_key => "entity_id"
  has_many :entity_tags, dependent: :destroy, :conditions => { :entity_type => 2 }, :foreign_key => "entity_id"
  has_many :entity_contacts, dependent: :destroy, :conditions => { :entity_type => 2 }, :foreign_key => "entity_id"
end

app/models/crm_contact.rb
class CrmContact < ActiveRecord::Base  
  attr_accessible :title, :company_id, :company_name, :first_name, :industry, :is_company, :last_name, :notes, :status_id, :tenant_id
  has_one :phone,  :class_name => "CrmContactInfo", :conditions => { :type_id => 0 }
  has_one :email,  :class_name => "CrmContactInfo", :conditions => { :type_id => 1 }
  has_many :crm_contact_infos, dependent: :destroy
  has_many :relationship_events, dependent: :destroy, :conditions => { :entity_type => 1 }, :foreign_key => "entity_id"
  has_many :tasks, dependent: :destroy, :conditions => { :entity_type => 1 }, :foreign_key => "entity_id"
  has_many :entity_tags, dependent: :destroy, :conditions => { :entity_type => 1 }, :foreign_key => "entity_id"
  has_many :deals
  belongs_to :company, :class_name => "CrmContact",  :foreign_key => "company_id"
  belongs_to :status, :class_name => "ListItem"
  def is_company_text
    ARRAY_CONTACT_TYPE[is_company][0]
  end
  def company_title
    company.title if company
  end
end

app/models/crm_contact_info.rb
class CrmContactInfo < ActiveRecord::Base
  # TYPES = [ {:1 => "Check", :2=>"Credit card", :3=>"Purchase order" }]
  belongs_to :tenant
  belongs_to :crm_contact
  attr_accessible :category_id, :contact_id, :tenant_id, :data, :is_primary, :type_id
  # validates :type, :inclusion =>   { :in => TYPES.keys.map(&:to_s) }
  def type
    @a=ARRAY_CONTACT_INFO_TYPE[type_id]
    @a[0] if @a
  end
  def category
    @a=ARRAY_CONTACT_INFO_CATEGORY[category_id]
    @a[0] if @a
  end
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  attr_accessible :actual_close_date, :bid_currency, :bid_type, :bid_value, :crm_contact_id, :deal_milestone_id, :deal_milestone_probability, :description, :expected_close_date, :per_period_value, :responsible, :tenant, :title
  has_many :relationship_events, dependent: :destroy, :conditions => { :entity_type => 3 }, :foreign_key => "entity_id"
  has_many :tasks, dependent: :destroy, :conditions => { :entity_type => 3 }, :foreign_key => "entity_id"
  has_many :entity_tags, dependent: :destroy, :conditions => { :entity_type => 3 }, :foreign_key => "entity_id"
  has_many :entity_contacts, dependent: :destroy, :conditions => { :entity_type => 3 }, :foreign_key => "entity_id"
end

app/models/deal_milestone.rb
class DealMilestone < ActiveRecord::Base
  belongs_to :tenant
  attr_accessible :color, :description, :probability, :sort_order, :status, :title
end

app/models/entity_contact.rb
class EntityContact < ActiveRecord::Base
  attr_accessible :entity_type, :crm_contact_id, :entity_id
  belongs_to :crm_contact
  def crm_contact111
    CrmContact.find(entity_contact.crm_contact_id).title
  end
end

app/models/entity_tag.rb
class EntityTag < ActiveRecord::Base
  attr_accessible :entity_id, :entity_type, :tag_id
  validates :tag_id, :uniqueness => { :scope => [:entity_id, :entity_type],
    :message => "should happen once per year" }
end

app/models/field_description.rb
class FieldDescription < ActiveRecord::Base
  attr_accessible :entity_type, :label, :mask, :sort_order, :tenant, :type
end

app/models/field_value.rb
class FieldValue < ActiveRecord::Base
  attr_accessible :entity, :entity_type, :field, :tenant, :value
end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  attr_accessible :additional_params, :color, :description, :list_type, :sort_order, :tenant, :title
end

app/models/relationship_event.rb
class RelationshipEvent < ActiveRecord::Base
  attr_accessible :category_id, :content, :crm_contact_id, :entity_type, :entity_id, :have_files, :tenant_id
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :entity_type, :tenant, :title
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :category_id, :crm_contact_id, :deadline, :description, :entity_id, :entity_type, :is_closed, :responsible_id, :tenant_id, :title
  belongs_to :category
  def entity_object
    EntityObjectByChild(self)
  end
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  # GET /list_items
  # GET /list_items.json
  def index
    @list_items = ListItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @list_items }
    end
  end

  # GET /list_items/1
  # GET /list_items/1.json
  def show
    @list_item = ListItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list_item }
    end
  end

  # GET /list_items/new
  # GET /list_items/new.json
  def new
    @list_item = ListItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list_item }
    end
  end

  # GET /list_items/1/edit
  def edit
    @list_item = ListItem.find(params[:id])
  end

  # POST /list_items
  # POST /list_items.json
  def create
    @list_item = ListItem.new(params[:list_item])

    respond_to do |format|
      if @list_item.save
        format.html { redirect_to @list_item, notice: 'List item was successfully created.' }
        format.json { render json: @list_item, status: :created, location: @list_item }
      else
        format.html { render action: "new" }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /list_items/1
  # PUT /list_items/1.json
  def update
    @list_item = ListItem.find(params[:id])

    respond_to do |format|
      if @list_item.update_attributes(params[:list_item])
        format.html { redirect_to @list_item, notice: 'List item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_items/1
  # DELETE /list_items/1.json
  def destroy
    @list_item = ListItem.find(params[:id])
    @list_item.destroy

    respond_to do |format|
      format.html { redirect_to list_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def currentpage(controller)
    "current" if params[:controller] == controller
  end
  def EntityObjectByChild(child)
    if child.entity_type
    case child.entity_type
    when 1
      CrmContact
    when 2
      CrmCase
    when 3
      Deal
    end.find(child.entity_id)
    end
  end
  def entity_object_path(entity_object)
     if entity_object then url_for(entity_object) else '' end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/crm_cases_helper.rb
module CrmCasesHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/list_items/_form.html.erb
<%= form_for(@list_item) do |f| %>
  <% if @list_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list_item.errors.count, "error") %> prohibited this list_item from being saved:</h2>

      <ul>
      <% @list_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :sort_order %><br />
    <%= f.number_field :sort_order %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/list_items/edit.html.erb
<h1>Editing list_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @list_item %> |
<%= link_to 'Back', list_items_path %>

app/views/list_items/index.html.erb
<h1>Listing list_items</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Sort order</th>
    <th>Color</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @list_items.each do |list_item| %>
  <tr>
    <td><%= list_item.title %></td>
    <td><%= list_item.sort_order %></td>
    <td><%= list_item.color %></td>
    <td><%= list_item.description %></td>
    <td><%= link_to 'Show', list_item %></td>
    <td><%= link_to 'Edit', edit_list_item_path(list_item) %></td>
    <td><%= link_to 'Destroy', list_item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New List item', new_list_item_path %>

app/views/list_items/new.html.erb
<h1>New list_item</h1>

<%= render 'form' %>

<%= link_to 'Back', list_items_path %>

app/views/list_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @list_item.title %>
</p>

<p>
  <b>Sort order:</b>
  <%= @list_item.sort_order %>
</p>

<p>
  <b>Color:</b>
  <%= @list_item.color %>
</p>

<p>
  <b>Description:</b>
  <%= @list_item.description %>
</p>


<%= link_to 'Edit', edit_list_item_path(@list_item) %> |
<%= link_to 'Back', list_items_path %>